#!/bin/bash

whatplatform () {
  cat /etc/issue | grep -i 'mint' > /dev/null && echo debian && return 0
  cat /etc/issue | grep -i 'kali' > /dev/null && echo debian && return 0

  if [ "$(uname)" = "Darwin" ]; then
    # Do something under Mac OS X platform
    echo "darwin"
  elif [ "$(expr substr $(uname -s) 1 10)" = "MINGW32_NT" ]; then
    # Do something under Windows NT platform
    return "$(expr substr $(uname -s) 1 10)"
  fi
}

vmx() {
  echo "[Hypervisor Detection] $1 is the one virtualizes this machine. proceeding..."
  sh /tmp/pde/`whatplatform`/guest/vmware.sh
}

vbox() {
  echo "[Hypervisor Detection] $1 is the one virtualizes this machine. proceeding..."
  sh /tmp/pde/`whatplatform`/guest/virtualbox.sh
}

vmopt() {
  HYPERV=`sudo dmidecode -s system-product-name`

  if [ "$HYPERV" = "VirtualBox" ]; then
    vbox $HYPERV
    return 0
  fi

  if [ "$HYPERV" = "VMware Virtual Platform" ]; then
    vmx $HYPERV
    return 0
  fi

  echo "[ERROR] This machine likely has none of Hypervisor. abort"
  return 1

}

preinstall_apt() {

  if [ -z `which ansible` ]; then
    export DEBIAN_FRONTEND=noninteractive
    sudo apt update
    sudo apt                               \
      -o Dpkg::Options::="--force-confdef" \
      -o Dpkg::Options::="--force-confold" \
    -yq dist-upgrade

    sudo apt install -y software-properties-common
    sudo apt-add-repository ppa:ansible/ansible
    sudo apt update
    sudo apt install -y ansible
    sudo chown -R -v $USER ~/.ansible
  fi

  which git || sudo apt install -y git

}

preinstall_dnf() {
  :
}

preinstall_brew() {

  if [ -z `which brew` ]; then
    # appleid required beforhand
    # is this better?
    xcode-select --install
    sudo xcodebuild -license
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
  fi
  if [ -z `which ansible` ]; then
    brew install ansible
  fi
  if [ -z `which git` ]; then
    brew install git
  fi

}

preinstall() {
  if [ "$(uname)" = "Darwin" ]; then
    echo "preinstall for macos"
    preinstall_brew
  elif which apt 2>/dev/null; then
    # Do something under GNU/Linux platform
    preinstall_apt
  elif which dnf 2>/dev/null; then
    # Do something under GNU/Linux platform
    preinstall_dnf
  fi
}

OSDIR=`whatplatform`
USER=`whoami`

echo "$OSDIR"
echo "$USER"


# Better to be separated context from below
#  echo Virtual Machine Optimization mode OSDIR=$OSDIR
#    vmopt
#    exit 0
#    ;;

preinstall
cd /tmp
test -d /tmp/pde || git clone https://github.com/o2346/pde
cd /tmp/pde

while getopts "dev" OPT ; do
  case $OPT in
    d)  echo Branch: Develop OSDIR=$OSDIR
        echo ansible playbook install.yml
        git checkout develop
        git pull --ff-only
        cd /tmp/pde/$OSDIR
        ansible-playbook install.yml -kK --connection=local
        ;;
    e)  echo Branch: Develop OSDIR=$OSDIR
        echo ansible playbook exam.yml
        git checkout develop
        git pull --ff-only
        cd /tmp/pde/$OSDIR
        ansible-playbook exam.yml -kK --connection=local
        ;;
    v)  echo Branch: Develop OSDIR=$OSDIR
        echo 'Set up target host vulnerable for handy'
        git checkout develop
        git pull --ff-only
        cd /tmp/pde/$OSDIR
        ./vulnerable.sh
        exit 0
        ;;
    *)
        ;;
  esac
done

if [ "$#" = 0 ]; then
  git checkout master
  git pull --ff-only
  cd /tmp/pde/$OSDIR
  ansible-playbook install.yml -kK --connection=local
  exit $?
fi
