# The program checks for configuration files in the following order:
# - $XDG_CONFIG_HOME/powermate.toml (usually ~/.config/powermate.toml)
# - /etc/powermate.toml
# You can override this and use a custom path by starting the program with the "-c" option.
# If a file cannot be found, the defaults settings correspond to the values in this file.

# Path to device:
dev = "/dev/input/powermate"

# Whether to daemonize the process or not:
daemonize = false

# How much (in percent) to change the volume for each step:
p = 0.6

# Custom commands (will disable default behavior).
# Set to an empty string to disable the default behavior without executing a custom command.
press_command = "xdotool search --name mpv | xargs -I{} xdotool key --window {} XF86AudioPlay" # Default: mute/unmute
long_press_command = "(xfce4-panel &); (xfwm4 --replace &)" #https://www.makeuseof.com/tag/refresh-linux-desktop-without-rebooting/
# clock_wise_command = "" # Default: increases the volume by p%
# counter_clock_wise_command = "" # Default: decreases the volume by p%
press_clock_wise_command = "xdotool search --name mpv | xargs -I{} xdotool key --window {} XF86AudioNext"
press_counter_clock_wise_command = "xdotool search --name mpv | xargs -I{} xdotool key --window {} XF86AudioPrev"

# Timeouts (in milliseconds)
long_press_ms = 2400

# Handy commands:
# xdotool key XF86AudioPlay
# xdotool key XF86AudioPrev
# xdotool key XF86AudioNext
# xdotool key XF86AudioLowerVolume
# xdotool key XF86AudioRaiseVolume
# xdotool key XF86AudioMute
# systemctl suspend

