---
- hosts: localhost
  vars:
  become: no
  tasks:
#
# Chomium setting ( gave up )
# Preferences file is overwridden at startup and no way found to prevent
#
# A file shown below is likely the target
# ~/.config/chromium/Default/Preferences
# The file would be installed with Chromium itself. It exists right after installation of Chomium.
# - name: Chromium Setting - modify JSON by node
#   command: node src/chromium.js

# gnome terminal setting ( gave up, doesn't work )
# gsettings list-recursively | grep -i org.gnome.Terminal
# ~/.gconf/apps/gnome-terminal/profiles
