---
- hosts: localhost
  vars:
    nodesetup: /tmp/node_setup.sh
    gituser: hoge
    gitemail: hoge@fuga.email
  become: no
  tasks:
  - name: git config username in global
    command: git config --global user.email "{{ gituser }}"
  - name: git config email in global
    command: git config --global user.name "{{ gitemail }}"

