---
- hosts: localhost
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
  become: no
  tasks:
  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - python-pip
    become: true

  - name: install pip(s)
    pip: name={{ item }} extra_args="-U"
    with_items:
      - pip
      - setuptools
      - csvkit
    become: true

  - name: sitecustomize.py
    blockinfile:
      dest: /etc/python2.7/sitecustomize.py
      insertafter: '^# install the apport exception handler if available'
      content: |
        import sys
        sys.setdefaultencoding('utf-8')
    become: true
