---
- hosts: localhost
  vars:
    nodesetup: /tmp/node_setup.sh
  become: no
  tasks:
  - name: copy autostart
    copy: >
      src=./sources.list
      dest=/etc/apt/sources.list
      mode=0644
    become: yes

