---
- hosts: localhost
  vars:
    font: 'MigMix 1M 16'
    font_monospace: 'Ricty Diminished Regular 15'
    font_titlebar: 'Migu 2M Bold 14'
  become: no
  tasks:
  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - fonts-ricty-diminished
      - fonts-migmix
    become: true

#
# Fonts
#
  - name: Fonts for Default
    command: gsettings set org.cinnamon.desktop.interface font-name "{{ font }}"
  - name: Fonts for Desktop
    command: gsettings set org.nemo.desktop font "{{ font }}"
  - name: Fonts for Document
    command: gsettings set org.gnome.desktop.interface document-font-name "{{ font }}"
  - name: Fonts for monospace
    command: gsettings set org.gnome.desktop.interface monospace-font-name "{{ font_monospace }}"
  - name: Fonts for Window Titlebar
    command: gsettings set org.cinnamon.desktop.wm.preferences titlebar-font "{{ font_titlebar }}"

