---
- hosts: localhost
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
    android_studio_url: https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0
    android_studio_name: android-studio-ide-162.4069837-linux.zip
    android_studio_checksum: 1383cfd47441e5f820b6257a1bdd683e0e980bc76c7f2027ef84dc2e6ad2f17f
    android_studio_parentdir: /usr/local/
    android_studio_dir: android-studio
  become: no
  tasks:

#
# Android
#https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - name: check if android_studio_zip exists
    stat: path={{ downloads }}/{{ android_studio_name }}
    register: has_android_studio_zip
  - name: show stat if NO android_studio_zip exists
    debug: var=has_android_studio_zip
    when: not has_android_studio_zip.stat.exists
  - name: download Android Studio (sh256sum)
    get_url: >-
      url={{ android_studio_url }}/{{ android_studio_name }}
      dest={{ downloads }}
      sha256sum={{android_studio_checksum}}
      force=no
    become: true
    when: not has_android_studio_zip.stat.exists
  - name: Unzip Android Studio
    command: unzip -o {{ downloads }}/{{ android_studio_name }}
    args:
        chdir: "{{ android_studio_parentdir }}"
    become: true
  - name: kvm install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
     - qemu-kvm
     - kvm
     - virt-manager
     - libvirt-bin
     - bridge-utils
    become: true
  - name: start libvirt-bin
    service: name=libvirt-bin state=running enabled=yes
    become: true
  #http://acchi-muite-hoi.hatenablog.com/entry/2016/08/18/102709
  - name: add vhost_net to load module
    lineinfile:
      dest: /etc/modules
      line: 'vhost_net'
    become: true
  - name: chown
    file: >-
      path={{ android_studio_parentdir }}{{ android_studio_dir }}
      group=root
      owner={{ansible_user_id}}
    become: true
  # http://www.techscore.com/blog/2016/08/26/debianstretch%E3%81%A7%E3%80%81android-studio2-1-3-%E3%81%AE-%E5%BF%AB%E9%81%A9-%E3%81%AAavd%E8%B5%B7%E5%8B%95%E7%92%B0%E5%A2%83%E3%82%92%E5%AE%9F%E7%8F%BE%E3%81%99%E3%82%8B/
  - name: adduser
    user: >-
      name={{ansible_user_id}}
      groups=root,libvirtd
    become: true

