---
- hosts: localhost
  vars:
    nodesetup: /tmp/node_setup.sh
  become: no
  tasks:
  - name: create ~/.ssh directory if it doesn't exist
    file:
      path: ~/.ssh
      state: directory
      mode: 0755

