---
- hosts: localhost
  vars:
    nodesetup: /tmp/node_setup.sh
  become: no
  tasks:
  - name: install package
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - exfat-fuse
      - exfat-utils
    become: true
