---
- hosts: localhost
  vars:
  become: no
  tasks:

#
# Dotfiles
#
  - name: download dotfiles
    git:
      repo: https://gist.githubusercontent.com/whateverjp/f43ec7ea2687697cc1ad
      dest: ~/Documents/.dotfiles
  - name: deploy dotfiles
    command: sh ~/Documents/.dotfiles/deploy.sh

#
# Chomium setting ( gave up )
# Preferences file is overwridden at startup and no way found to prevent
# related? https://wiki.archlinux.org/index.php/Chromium/Tips_and_tricks#Chromium_overrides.2Foverwrites_Preferences_file
#
# A file shown below is likely the target
# ~/.config/chromium/Default/Preferences
# The file would be installed with Chromium itself. It exists right after installation of Chomium.
# - name: Chromium Setting - modify JSON by node
#   command: node src/chromium.js

# gnome terminal setting ( gave up, doesn't work )
# gsettings list-recursively | grep -i org.gnome.Terminal
# ~/.gconf/apps/gnome-terminal/profiles
