---
- hosts: localhost
  vars:
    nodesetup: /tmp/node_setup.sh
    gituser: hoge
    gitemail: hoge@fuga.email
    font: 'MigMix 1M 16'
  become: no
  tasks:
  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - fonts-ricty-diminished
      - fonts-migmix
    become: true

#
# Fonts
#
  - name: Fonts for Default
    command: gsettings set org.cinnamon.desktop.interface font-name "{{ font }}"
  - name: Fonts for Desktop
    command: gsettings set org.nemo.desktop font "{{ font }}"

