---
- hosts: "{{ given_host | default('all') }}"
  tasks:
  - name: echo hosts
    debug:
      msg: "System:{{ inventory_hostname }} user:{{ ansible_user_id }}"

  - name: command uname
    command: uname
    register: uname_result
    changed_when: False

  - debug: var=uname_result.stdout_lines # stdout => stdout_lines
    when: uname_result | success

