---
- hosts: "{{ given_host | default('localhost') }}"
  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - ssh
    become: true
  - name: command ifconfig
    command: ip a
    register: ipa_result
    changed_when: False

  - debug: var=ipa_result.stdout_lines # stdout => stdout_lines
    when: ipa_result | success

