---
- hosts: "{{ given_host | default('localhost') }}"
  vars:
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/dupes
      - homebrew/versions
      - homebrew/boneyard
      - homebrew/binary

    homebrew_cask_packages:
      - name: appcleaner
      - name: virtualbox
      - name: vagrant
      - name: atom
      - name: google-chrome
      - name: firefox

    homebrew_packages:
      - name: awscli
      - name: python
      - name: python3
      - name: tig
      - name: tmux
      - name: zsh
  become: no
  tasks:
  - name: homebrew update
    homebrew:
      update_homebrew: yes

  - name: homebrew tap
    homebrew_tap:
      name: '{{ item }}'
      state: present
    with_items: '{{ homebrew_taps }}'

  - name: homebrew cask packages install
    homebrew_cask: name={{ item.name }} state=installed
    # ※1 GUIツールをインストールする場所を `/Application` に固定
    environment:
      HOMEBREW_CASK_OPTS: "--appdir=/Applications"
    with_items: '{{ homebrew_cask_packages }}'

  - name: homebrew packages install
    homebrew:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
    with_items: '{{ homebrew_packages }}'
