---
- hosts: "{{ given_host | default('localhost') }}"
  vars:
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/dupes
      - homebrew/versions
      - homebrew/boneyard
      - homebrew/binary

    homebrew_cask_packages:
      - name: appcleaner
      - name: virtualbox
      - name: vagrant
      - name: atom
      - name: google-chrome
      - name: firefox
      - name: diffmerge
      - name: google-japanese-ime
      - name: p4merge
      - name: vlc
      - name: dropbox
      - name: iterm2
      - name: skitch
      - name: xquartz
      - name: filezilla
      - name: keepassx
      - name: sourcetree
      - name: libreoffice
      - name: geekbench
      - name: macdown
    homebrew_packages:
      - name: awscli
      - name: python
      - name: python3
      - name: tig
      - name: tmux
      - name: zsh
      - name: cmake
      - name: diff-pdf
      - name: doxygen
      - name: emacs
      - name: ffmpeg
      - name: fontconfig
      - name: fontforge
      - name: freetype
      - name: gnu-sed
      - name: gnutls
      - name: htop
      - name: jasper
      - name: jpeg
      - name: lame
      - name: macvim
      - name: mp3splt
      - name: nasm
      - name: net-snmp
      - name: nettle
      - name: nkf
      - name: nmap
      - name: node
      - name: openssl
      - name: python
      - name: readline
      - name: reattach-to-user-namespace
      - name: sqlite
      - name: texi2html
      - name: trash
      - name: tree
      - name: utf8proc
      - name: w3m
      - name: webp
      - name: wget
      - name: wine
      - name: wireshark
      - name: wxmac
      - name: yasm

  become: no
  tasks:
  - name: homebrew update
    homebrew:
      update_homebrew: yes

  - name: homebrew tap
    homebrew_tap:
      name: '{{ item }}'
      state: present
    with_items: '{{ homebrew_taps }}'

  - name: homebrew cask packages install
    homebrew_cask: name={{ item.name }} state=installed
    # ※1 GUIツールをインストールする場所を `/Application` に固定
    environment:
      HOMEBREW_CASK_OPTS: "--appdir=/Applications"
    with_items: '{{ homebrew_cask_packages }}'

  - name: homebrew packages install
    homebrew:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
    with_items: '{{ homebrew_packages }}'
