---
- hosts: "{{ given_host | default('localhost') }}"
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
  become: no
  tasks:

#
# plantUML
# https://www.hiroom2.com/2018/07/02/ubuntu-1804-plantuml-en/
  - name: install dependencies for PlantUML
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
     - graphviz
     - default-jre
    become: true
  - name: Creates directory
    file:
      path: /opt/plantuml
      state: directory
    become: true
  - name: check existence of plantuml
    stat: path=/opt/plantuml/plantuml.jar
    register: has_plantml
  - name: download PlantUML
    get_url:
      url: http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
      dest: /opt/plantuml/
      mode: 0555
    become: true
    when: not has_plantml.stat.exists

