---
- hosts: "{{ given_host | default('localhost') }}"
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
  become: no
  tasks:

  #https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html
  - name: Check
    command: ls .uc
    register: is_uc_installed
    ignore_errors: true
    args:
      chdir: ~/

  - name: Print on succeeded
    debug:
      msg: "{{ is_uc_installed.stdout }}"
    when: is_uc_installed is succeeded

  - name: Print on failed
    debug:
      msg: "nothing found"
    when: is_uc_installed is failed

  - name: install Dotfiles
    shell: curl 'https://raw.githubusercontent.com/o2346/happy-scripts/develop/install.uc.sh' | bash -s - https://gist.github.com/o2346/e091ea8f6bf963d6a170a88579a3db08
    args:
      chdir: ~/
    register: uc_install_log
    when: is_uc_installed is failed
  - name: Print
    debug:
      msg: "{{ uc_install_log.stdout }}"
    when: is_uc_installed is failed
