---
- hosts: "{{ given_host | default('localhost') }}"
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
  become: no
  tasks:

  #https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html
  - name: Check
    command: which node
    register: is_node_installed
    ignore_errors: true

  - name: Print on succeeded
    debug:
      msg: "{{ is_node_installed.stdout }}"
    when: is_node_installed is succeeded

  - name: Print on failed
    debug:
      msg: "nothing found"
    when: is_node_installed is failed

