---
- hosts: "{{ given_host | default('localhost') }}"
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
  become: no
  tasks:

#
# mitmdump
#
  - name: install dependencies for mitmproxy
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
     - python3-dev
     - python3-pip
     - libffi-dev
     - libssl-dev
    become: true

  - name: upgrade pip
    pip:
      name: pip
      executable: pip3
      state: latest
    become: true

  - command: sudo pip3 install -U pip
    become: true

  - name: mitmproxy
    command: sudo pip3 install --ignore-installed mitmproxy
    become: true

