---
- hosts: "{{ given_host | default('localhost') }}"
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
  become: no
  tasks:

  - name: Check
    command: cat /etc/os-release
    register: osrelease

  - name: Print version
    debug:
      msg: "os-release: {{ osrelease.stdout }}"

