---
- hosts: "{{ target | default('localhost') }}"
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
  become: no
  tasks:

#
#Sample tasks
#
  #https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html
  - name: Check
    command: cat /etc/issue
    register: etc_issue
    ignore_errors: true
    args:
      chdir: ~/
    become: yes

  - name: Print on succeeded
    debug:
      msg: "{{ etc_issue.stdout }}"
    when: etc_issue is succeeded

  - name: Print on failed
    debug:
      msg: "nothing found"
    when: etc_issue is failed

  #ansible-playbook -u mint -e target=localguest --extra-vars "ansible_sudo_pass=UNDEFINED" -i hosts  exam.yml
  - name: Print how re-run playbook for handy
    debug:
      msg: "ansible-playbook {{playbook_dir}}/exam.yml --connection=local --extra-vars 'ansible_sudo_pass=UNDEFINED'"
#
#
#END Sample tasks

