---
- hosts: "{{ target | default('localhost') }}"
  vars:
    downloads: /home/{{ansible_user_id}}/Downloads
  become: no
  tasks:

  #https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html
  - name: Check
    command: cat /etc/issue
    register: etc_issue
    ignore_errors: true
    args:
      chdir: ~/
    become: yes

  - name: Print on succeeded
    debug:
      msg: "{{ etc_issue.stdout }}"
    when: etc_issue is succeeded

  - name: Print on failed
    debug:
      msg: "nothing found"
    when: etc_issue is failed

  #ansible-playbook -u mint -e target=localguest --extra-vars "ansible_sudo_pass=UNDEFINED" -i hosts  exam.yml
  - name: Print how re-run playbook for handy
    debug:
      msg: "ansible-playbook {{playbook_dir}}/exam.yml --connection=local --extra-vars 'ansible_sudo_pass=UNDEFINED'"

  #
  # Set timezone
  #
  #On GUI, it accepts 'Japan' though
  #https://docs.ansible.com/ansible/2.3/timezone_module.html
  - name: set timezone to Asia/Tokyo
    timezone:
      name: Asia/Tokyo
    become: yes

  #
  # Startup apps on boot
  #
    #https://superuser.com/a/1253718
    #https://wiki.archlinux.org/index.php/systemd#Basic_systemctl_usage
    #https://askubuntu.com/questions/903354/difference-between-systemctl-and-service-commands
  - name: copy scrpts to /usr/local/bin
    copy: >
      src=./system/
      dest=/etc/systemd/system
      mode=777
    become: true

  #
  # Slimblade Trackball
  #
  - name: Device - Slimblade Trackball - copy scrpts to /usr/local/bin
    copy: >
      src=./devices/trackball/trackball.sh
      dest=/usr/local/bin
      mode=755
    become: true

  #
  # Griffin Powermate
  #
  - name: Device - Griffin Powermate - copy scrpts to /usr/local/bin
    copy: >
      src=./devices/powermate/
      dest=/usr/local/bin
      mode=755
    become: true
  - name: Device - Griffin Powermate - Invoke command first
    command: /usr/local/bin/powermate.sh
    become: true
    ignore_errors: true
  - name: Device - Griffin Powermate - Make sure a service is running
    systemd:
      #state: started
      enabled: yes
      name: powermate
    become: true

